### ISSUE TITLE
`,` is not allowed in an ID

### ISSUE THREAD

**Issue by erkal** [brandly/elm-dot-lang#5]
If we want to encode things like [point](https://www.graphviz.org/doc/info/attrs.html#k:point) in the way graphviz does, than we need to allow `,` in IDs.
I believe that adding `,` to [this line](https://github.com/brandly/elm-dot-lang/blob/657bda40d480a21eb4c6b0a33fb2734600851a32/src/DotLang.elm#L666) would solve the problem.

Maybe all the special symbols which are used in DOT language (I mean things like `{`,`=`,`;`, `[` and so on) should be allowed in IDs. 
For example, when I tried to put json strings as ID's, the decoding didn't work because those symbols like `{` which are common to both json and dot, caused errors when parsing.

**Comment by brandly** [comment]
you're right. `toString` has some deficiencies.

the language spec says

> Any string of alphabetic ([a-zA-Z\200-\377]) characters, underscores ('_') or digits ([0-9]), not beginning with a digit; 

what do they mean by `\200-\377`? is that a range of utf-8 characters? 

potentially, within `toString`, the code should say "if any character is _outside_ this whitelist, wrap it in quotation marks" instead of having a blacklist of symbols. any idea what that looks like in Elm? hah

**Comment by erkal** [comment]
> what do they mean by \200-\377? is that a range of utf-8 characters?

I think it is ASCII: http://www.ascii-code.net/

**Comment by erkal** [comment]
I fear that allowing characters like `}` in the IDs can break the parser.

**Comment by brandly** [comment]
any characters, like `{`, should be fine as long as they're wrapped in quotation marks. 

in [the failing test](https://github.com/brandly/elm-dot-lang/commit/710c0bd293747ee40e438c9714ab291c9f049148) i posted, parsing the `#` in an ID is fine already since it's wrapped in quotes. similarly, parsing arbitrary JSON in an ID should be fine, now that [i fixed handling escaped quotation marks](https://github.com/brandly/elm-dot-lang/commit/29462ca13c0163e3ef32b0a0016a52b6d571c4bf).

as mentioned above, `toString` needs work. the current implementation of `showId` is short-sighted. i could keep adding characters like `{` to the blacklist that triggers the need for quotation marks, but i think the correct way is to define a whitelist of characters that don't need quotation marks and wrap the ID if any character falls outside those bounds.

> The octal codes for Extended Character Set (ANSI) go from 200 to 377:

good find! i'll figure out how Elm handles these things, and get both these issues fixed. thanks again

**Comment by erkal** [comment]
I think the easiest way would be to have a set of whitelist characters
```elm
whiteList : Set Characters
whiteList =
    Set.fromList [ '{', ',', ... ]
```
and check ist with `Set.member`

**Comment by erkal** [comment]
> Any string of alphabetic ([a-zA-Z\200-\377]) characters, underscores ('_') or digits ([0-9]), not beginning with a digit;

Here is a suggestion:

```elm
isInWhiteList : Char -> Bool
isInWhiteList char =
    let
        asciiOctalFrom200To377 : Set Char
        asciiOctalFrom200To377 =
            Set.fromList [{- here come the characters with that code -}]
    in
    List.any identity
        [ Char.isLower char
        , Char.isUpper char
        , '_' == char
        , Char.isDigit char
        ]


beginningWithADigit : String -> Bool
beginningWithADigit string =
    case String.uncons string of
        Just ( c, _ ) ->
            Char.isDigit c

        Nothing ->
            False


hasACharacterNotInWhiteList : String -> Bool
hasACharacterNotInWhiteList =
    String.toList >> List.any (isInWhiteList >> not)


shouldBeQuoted : String -> Bool
shouldBeQuoted s =
    {- `String.isEmpty s` could prevent current parsing errors caused the empty strings. -}
    String.isEmpty s
        || beginningWithADigit s
        || hasACharacterNotInWhiteList s
```
